export type PropertyType = {
    aggregationTag: string;
    archipelagoId: string;
    buildings: number;
    builtBy: string;
    businessInterruptionInsuredValue: number;
    constructionType: string;
    constructionTypeATC: string;
    constructionTypeISO: string;
    constructionTypeRMS: string;
    contentInsuredValue: number;
    fireEstimatedMaximumLoss: null | number;
    fireProbableMaximumLoss: null | number;
    floorArea: number;
    geoCodeIcon: string;
    geoCodeType: string;
    hazards: number;
    quakeZone: null | string;
    floodZone: null | string;
    windZone: null | string;
    highPriorityEngineeringRecommendations: null | number;
    id: string;
    lastEngineeringVisit: null | string;
    location: string;
    locationId: string;
    locationName: string;
    city: string;
    county: null | string;
    country: string;
    latitude: number;
    longitude: number;
    street: string;
    state: string;
    zip: null | string;
    pictures: any;
    lossEngineeringReportPresent: null | string;
    managedBy: string;
    modelling: number;
    natureOfLastUpgrade: null | string;
    nrOfBuildings: number;
    nrOfStories: number;
    occupancyType: string;
    occupancyTypeATC: string;
    occupancyTypeSIC: string;
    occupancyTypeNAICS: string;
    multiTenant: number;
    primaryTenantNAICS: string;
    quakeModifierAppendagesAndOrnamentation: string;
    quakeModifierBaseIsolation: string;
    quakeModifierBuildingExterior: string;
    completedQuakeModifiers: string;
    quakeModifierConstructionQuality: string;
    quakeModifierCrippleWalls: string;
    quakeModifierEngineeredFoundation: string;
    quakeModifierEqslSusceptibility: string;
    quakeModifierEquipmentEqBracing: string;
    quakeModifierEquipmentSupportMaintenance: string;
    quakeModifierExteriorWalls: string;
    quakeModifierFrameBoltedToFoundation: string;
    quakeModifierInteriorWalls: string;
    quakeModifierPounding: string;
    quakeModifierRedundancy: string;
    quakeModifierSetbacksAndOverhangs: string;
    quakeModifierShapeConfiguration: string;
    quakeModifierShortColumnCondition: string;
    quakeModifierSoftStory: string;
    quakeModifierSprinklerType: string;
    quakeModifierStructuralUpgrade: string;
    quakeModifierTank: string;
    quakeModifierTiltUpRetrofit: string;
    quakeModifierTorsion: string;
    quakeModifierUrmRetrofit: string;
    quakeScenarioEstimatedLoss: null | string;
    quakeScenarioUpperLoss: null | string;
    replacementCostMethodology: string;
    replacementCostPerSquareFootage: number;
    roofDetails: number;
    roofImage: null;
    roofSystem: null | string;
    roofInstallYear: null | number;
    roofEstimatedReplacementYear: null | number;
    seismicStatus: string | null;
    yearOfSeismicUpgrade: number;
    sprinklers: number;
    sprinklersSystem: string;
    percentageSprinklered: number;
    structuralDescription: string | null;
    totalInsuredValue: number;
    windAndFloodModifierArchitecturalElements: null;
    windAndFloodModifierAsiaBasementFloodProtection: null;
    windAndFloodModifierAtticInsulation: null;
    windAndFloodModifierBuildingElevation: string;
    windAndFloodModifierBuildingHeight: string;
    windAndFloodModifierChimneys: null;
    windAndFloodModifierCladding: string;
    windAndFloodModifierCommercialAppurtenantStructures: string;
    completedWindAndFloodModifiers: string;
    windAndFloodModifierConstructionQuality: string;
    windAndFloodModifierContamination: null;
    windAndFloodModifierContentsVulnerabilityDueToWater: null;
    windAndFloodModifierFlashingAndCopingQuality: string;
    windAndFloodModifierFloodFoundationType: null;
    windAndFloodModifierFloodMissiles: string;
    windAndFloodModifierFloodProtection: string;
    windAndFloodModifierFloorType: string;
    windAndFloodModifierFrameFoundationConnection: string;
    windAndFloodModifierGroundElevation: string;
    windAndFloodModifierGroundLevelEquipment: string;
    windAndFloodModifierIceDamProtection: null;
    windAndFloodModifierMechElecEquipOnRoof: null;
    windAndFloodModifierNaBasementFloodProtection: string;
    windAndFloodModifierOnlyTreeDensity: null;
    windAndFloodModifierOpeningProtection: string;
    windAndFloodModifierPlumbingInsulation: null;
    windAndFloodModifierResidentialAppurtenantStructures: string;
    windAndFloodModifierRoofAge: string;
    windAndFloodModifierRoofAnchor: string;
    windAndFloodModifierRoofEquipmentWindBracing: string;
    windAndFloodModifierRoofGeometry: string;
    windAndFloodModifierRoofInstallYear: null;
    windAndFloodModifierRoofSheathingAttachment: string;
    windAndFloodModifierRoofSystemCovering: string;
    windAndFloodModifierRoofVentilation: null;
    windAndFloodModifierSnowGuards: null;
    windAndFloodModifierUkEuBasementFloodProtection: null;
    windAndFloodModifierUkEuSkPhFloodMissiles: null;
    windAndFloodModifierVerticalExposureDistribution: null;
    windAndFloodModifierWindMissiles: null;
    yearBuilt: number;
    yearLastUpgraded: number | null;
    yearsUnderManagement: number;
  };